config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'

  root 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: {maximum: 25}      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :remember_me)}
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end


    
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase 
     "https://www.gravatar.com/avatar/40ee3dd520e7e3ddd41a163a369f248c.jpg?d=identicon&s=40"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code4Pro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "shared/header" %>
  <%= render partial: "shared/message" %>
       
  <main>
    <div class="container"> 
        <%= yield %>
    </div>
  </main>
     
  <%= render partial: "shared/footer" %>

  </body>

      <script>

               $(".button-collapse").sideNav();
        $(".dropdown-button").dropdown();

    </script>
</html>

app/views/pages/about.html.erb
<h2>About</h2>


  <div class="card z-depth-3">
    <div class="card-content white-text">
      <div class="row">
        <div class="col m6">
          <div class="card-panel teal lighten-1 z-depth-1">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                    Alias sit accusamus veritatis, eveniet vel laboriosam 
                    nemo harum reprehenderit. Laborum labore exercitationem 
                    beatae enim iste reprehenderit incidunt dolor architecto 
                    necessitatibus facere!
          </div>
        </div>

        <div class="col m6">
          <div class="card-panel teal lighten-1 z-depth-1">
            <div class="row">
              <div class="col m3">
                 <%= image_tag  "kolya.jpg", class: "circle responsive-img" %>
              </div>

              <div class="col m9">
                <span class="white-text">
                  <h5>kolya</h5>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                    Alias sit accusamus veritatis, eveniet vel laboriosam 
                    nemo harum reprehenderit. Laborum labore exercitationem 
                    beatae enim iste reprehenderit incidunt dolor architecto 
                    necessitatibus facere!
                  </span>
                </div>
              </div>
            </div>
         </div>
  
     </div>
    </div>
  </div>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer brown lighten-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Code4Pro</h5>
                <p class="grey-text text-lighten-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                Laboriosam deserunt id, officiis nam eius, dolores quae voluptatibus aliquid cum perspiciatis 
                sint quo. Error incidunt consequatur eveniet qui porro temporibus repellat.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Social</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2018 Copyright Code4Pro
            <%= link_to  "About Us", pages_about_path, :class => "grey-text text-lighten-4 right" %>
            </div>
          </div>
        </footer>

app/views/shared/_header.html.erb
<header>
    <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
      <li><%= link_to  "My Profile", edit_user_registration_path %></li>
      <li><a href="#!">My Courses</a></li>
      <li class="divider"></li>
      <li><%= link_to  "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>

    <ul id="dropdown2" class="dropdown-content">
      <li><%= link_to  "My Profile", edit_user_registration_path %></li>
      <li><a href="#!">My Courses</a></li>
      <li class="divider"></li>
      <li><%= link_to  "Log out", destroy_user_session_path, method: :delete %></li>
      
    </ul>

      <nav class="brown lighten-4 z-depth-2">
      <div class="container">
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">Code4Pro</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="#">Courses</a></li>
              <% if(!user_signed_in?) %>
                <li><%= link_to  "Sign Up", new_user_registration_path %></li>
                <li><%= link_to  "Login", new_user_session_path %></li>
              <% else %>
              <!-- Dropdown Trigger -->
                <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
                  <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
                  <%=current_user.name %><i class="material-icons right">arrow_drop_down</i></a>
                </li>
              <% end %> 
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="#">Courses</a></li>
                        <% if(!user_signed_in?) %>
                <li><%= link_to  "Sign Up", new_user_registration_path %></li>
                <li><%= link_to  "Login", new_user_session_path %></li>
              <% else %>
              <!-- Dropdown Trigger -->
                <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
                  <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
                  <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a>
                </li>
              <% end %>       
          </ul>
        </div>
        </div>
      </nav>
  </header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
    toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>